### ISSUE TITLE
Remove 'assembly/contracts/' from asc -o path

### ISSUE THREAD

**Issue by 0xSwapFeeder** [massalabs/massa-sc-compiler#13]
In order to make a usable 'build' directory (with transformers for instance), we need the 'build' directory to be the root of the mirrored build files.

Lets say we have a contract placed as following 'project/assembly/contracts/my_sub_dir/main.ts'.
The built files should be in 'project/build/my_sub_dir/*' and not in 'project/build/assembly/contracts/my_sub_dir/*'

This happens when building with -r option in the massa-standard contracts.

This can be fixed with .replace('assembly/contracts/', '') on the -o option of asc.

**Comment by 0xSwapFeeder** [comment]
@Ben-Rey. from the discussion on transformers this morning.

**Comment by Ben-Rey** [comment]
Ok you will do the PR ?
